apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: chirpstack-simulator
  name: chirpstack-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chirpstack-simulator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: chirpstack-simulator
    spec:
      containers:
        - args:
            - chirpstack-simulator
          image: gcr.io/vu-james-celli/chirpstack-simulator:latest
          name: chirpstack-simulator
          # ports:
          #   - containerPort: 9000
          resources: {}
      restartPolicy: Always
