apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    # prometheus.io/scrape: "true"
    # prometheus.io/path: "/metrics"
    # prometheus.io/port: "9000"
    app: chirpstack-simulator
  labels:
    app: chirpstack-simulator
  name: chirpstack-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chirpstack-simulator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        app: chirpstack-simulator
      labels:
        app: chirpstack-simulator
    spec:
      containers:
        - args:
            - chirpstack-simulator
          image: gcr.io/vu-james-celli/chirpstack-simulator
          name: chirpstack-simulator
          ports:
            # - name: monitoring-port
            #   containerPort: 9000
          volumeMounts:
            - name: chirpstack-simulator
              mountPath: /chirpstack-simulator.toml
              subPath: chirpstack-simulator.toml
      volumes:
        - name: chirpstack-simulator
          configMap:
            name: chirpstack-simulator
